name: Build docker container and Push it

on:
    push:
        branches:
            - 'master'

jobs:
    build-and-publish:
        name: Build docker container and Push it
        runs-on: ubuntu-latest
        timeout-minutes: 5

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  ref: ${{ github.ref }}

            - name: Setup Google Cloud
              uses: 'google-github-actions/auth@v1'
              with:
                  credentials_json: ${{ secrets.GCP_CREDENTIAL }}

            - name: 'Set up Cloud SDK'
              uses: 'google-github-actions/setup-gcloud@v1'

            - name: Configure docker for artifact registry
              run: gcloud auth configure-docker us-west1-docker.pkg.dev

            - name: Build
              run: docker build ./ -t us-west1-docker.pkg.dev/nodejs-splat3-api/splat3api/express

            - name: Push
              run: docker push us-west1-docker.pkg.dev/nodejs-splat3-api/splat3api/express

            - name: Deploy to Cloud Run
              uses: 'google-github-actions/deploy-cloudrun@v1'
              with:
                  service: 'splat3-api'
                  image: us-west1-docker.pkg.dev/nodejs-splat3-api/splat3api/express
                  env_vars: |
                      PORT=3000
                      REDIS_HOST=${{ secrets.REDIS_HOST }}
                      REDIS_PORT=${{ secrets.REDIS_PORT }}
                      REDIS_USER=${{ secrets.REDIS_USER }}
                      REDIS_PASSWORD=${{ secrets.REDIS_PASSWORD }}

            - name: 'Use output'
              run: 'curl "${{ steps.deploy.outputs.url }}"'

        # - name: Update GCE container
        #   run: gcloud compute instances update-container instance-2 --container-image=us-west1-docker.pkg.dev/nodejs-splat3-api/splat3api/express --zone=us-west1-c
